### ISSUE TITLE
Update forum link

### ISSUE THREAD

**Issue by DanielOaks** [Kamal-Sadek/Liberal-Crime-Squad#5]
http://www.bay12games.com/forum/index.php?board=3.0 on the opening screen no longer exists, should be changed to http://www.bay12forums.com/smf/index.php?board=3.0

**Comment by Kamal-Sadek** [comment]
Will change as soon as I get home!

**Comment by DanielOaks** [comment]
Awesome, thanks!

**Comment by Kamal-Sadek** [comment]
Nah, thank you, can use any help I can get!
